### ISSUE TITLE
I use Scratch

### ISSUE THREAD

**Issue by ike2013-On-GitHub** [WorldLanguages/WorldLanguages#1]
Hello, WorldLanguages.
I use Scratch too and was wondering what happened to ScratchStats and why you left?

**Comment by WorldLanguages** [comment]
I still reply to Scratch comments from time to time

**Comment by ike2013-On-GitHub** [comment]
> I still reply to Scratch comments from time to time

Ok also I wonder how people get Location not given on there profile

**Comment by WorldLanguages** [comment]
It's not possible anymore
